import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>CodingBlogs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav className={styles.navbar}>
          <ul>
            <Link href='/'><li>Home</li></Link>
            <Link href='/about'><li>About</li></Link>
            <Link href='/blogspot'><li>Blogspot</li></Link>
          </ul>
        </nav>
      </header>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.center}>
          <h1>CodingBlogs</h1>
          <p>
            <code className={styles.code}>Blogs for coders</code>
          </p>
        </div>
          

      </main>
    </>
  );
}
